version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env.db
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    build: ./pay2u/.
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media
    depends_on:
      - db

  gateway:
    build: ./gateway/.
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    ports:
      - 8000:80