version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env.db
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    build: ./pay2u/.
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
      - media:/app/media
    depends_on:
      - db
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 pay2u.wsgi"

  gateway:
    build: ./gateway/.
    volumes:
      - static_volume:/app/collected_static
      - media:/media
    ports:
      - 8000:80
    depends_on:
      - backend
